---
dependency:
  name: galaxy
driver:
  name: docker    # instances from docker
lint:
  name: yamllint
platforms:
  - name: instance    # what instance to run
  image: centos:7 
provisioner:
  name: ansible     # run playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:       # 
  name: testinfra
  lint:
    name: flake8